[tools]
"aqua:nextest-rs/nextest/cargo-nextest" = "0.9.140"

[settings]
idiomatic_version_file_enable_tools = ["rust"]
lockfile = true

[tasks.ci]
run = "cargo check --workspace --all-targets --all-features"

[tasks.test]
run = "cargo nextest run --workspace --all-features"

[tasks.lint]
run = "cargo clippy --workspace --all-targets --all-features -- -D warnings"

[tasks.fmt]
run = "cargo fmt --all -- --check"
